### ISSUE TITLE
EDITOR LOADING ISSUE

### ISSUE THREAD

**Issue by truly6ve** [tneotia/html-editor-enhanced#211]
**Describe the bug**
The editor is working all fine and is very good in all respects. The only issue I am facing right now is; When I navigate to the page where this editor is, it doesn't load most of the time. I may need to go back and re-open the page. This is what I have to try most of the time as 70% it doesn't load.

As you can see in the first image it is loaded properly but in the second image, it is not loading the contents area of the Editor.

I am  trying this in Chrome and my Flutter version is: 2.8.1.

Hope to hear from you soon regarding its solution.

**Screenshots**
<img width="996" alt="Screenshot 2022-01-28 at 19 54 22" src="https://user-images.githubusercontent.com/72092249/151612805-2265bbc4-a45c-4f2a-9c33-7dfa615778ef.png">
<img width="996" alt="Screenshot 2022-01-28 at 19 55 16" src="https://user-images.githubusercontent.com/72092249/151612837-0a330158-7736-4280-b98d-6d71e640cacc.png">

**Comment by tneotia** [comment]
Is there anything of note in the logs when this happens? Seems like the HTML element iframe doesn't initialize properly?

**Comment by truly6ve** [comment]
Hi,

Thank you for your reply.

**The following message appears when the editor is not loaded properly:**

===========================================
TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at handleMessage (about:srcdoc:59:68)

===========================================

**And the below message appears every time when the page is loaded.**

===========================================

Height of Platform View type: [ehCS4r2mA-19sw==] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [ehCS4r2mA-19sw==] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.

===========================================

**Comment by truly6ve** [comment]
Hi,

Below is the detail of how the code is used:

final HtmlEditorController _htmlEditingController = HtmlEditorController();
===Getting data from APIs:
**__htmlEditingController.setText(emailTemplate['email_body']);_**

and the Editor settings is as below:

`HtmlEditor(
                          htmlEditorOptions: const HtmlEditorOptions(
                              hint: 'Your text here...',
                              shouldEnsureVisible: true),
                          htmlToolbarOptions: const HtmlToolbarOptions(
                              toolbarType: ToolbarType.nativeGrid,
                              defaultToolbarButtons: [
                                StyleButtons(),
                                FontSettingButtons(fontSizeUnit: false),
                                FontButtons(clearAll: false),
                                ColorButtons(),
                                ListButtons(listStyles: false),
                                ParagraphButtons(
                                    textDirection: false,
                                    lineHeight: false,
                                    caseConverter: false),
                                InsertButtons(
                                    picture: true,
                                    video: false,
                                    audio: false,
                                    table: true,
                                    hr: true,
                                    otherFile: false),
                              ]),
                          controller: _htmlEditingController),`

**Comment by sscast** [comment]
I noticed the same problem.. At the beginning it was always okay in browsers on a computer, but not okay in browsers on my phone. Now on computer it shows the same problem. 

Also I've been wondering how to set a height for the editor, it doesn't seem allowing that?

**Comment by sscast** [comment]
> Hi,
> 
> Thank you for your reply.
> 
> **The following message appears when the editor is not loaded properly:**
> 
> =========================================== TypeError: Cannot read properties of undefined (reading 'setAttribute') at handleMessage (about:srcdoc:59:68)
> 
> ===========================================
> 
> **And the below message appears every time when the page is loaded.**
> 
> ===========================================
> 
> Height of Platform View type: [ehCS4r2mA-19sw==] may not be set. Defaulting to `height: 100%`. Set `style.height` to any appropriate value to stop this message. Width of Platform View type: [ehCS4r2mA-19sw==] may not be set. Defaulting to `width: 100%`. Set `style.width` to any appropriate value to stop this message.
> 
> ===========================================

Hi @tneotia,  It's similar error for me too. Is it because somewhere the return value is null/nil? I don't know how to debug Javascript. :( Hope you know how to fix it. 
```
TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('note-editable')[0].setAttribute')
handleMessage — about:srcdoc:76
```

Thanks.

**Comment by tneotia** [comment]
Apologies, I have been extremely busy recently having started a new job, and currently don't have much time to look into this. I will see if I can find a solution in the near future.

**Comment by reke592** [comment]
possible because of CSP header

**Comment by truly6ve** [comment]
> possible because of CSP header

Sorry, what's CSP?

**Comment by reke592** [comment]
Content security policy, in the package there is an IFrame that loads the editor, on my case I encountered the same issue when I tried to render the index.html in backend to inject some meta-tags,  I need to include the script-src 'self' 'unsafe-inline' to load the editor.

**Comment by ervindobri** [comment]
Currently facing the same issue on Chrome. Flutter 2.10.4, latest version of package. No html renderer

**Comment by ZdenekKrcal** [comment]
Hi guys, I have same issues. :-(. It is not possible to use it for the web now becouse of that.

**Comment by tdh8316** [comment]
I'm facing the same problem on all of the available browsers.

**Comment by truly6ve** [comment]
Hi,

I have fixed it. Simply set "autoAdjustHeight" as "false" and it'll fix the issue.

```
                           HtmlEditor(
                              htmlEditorOptions: const HtmlEditorOptions(
                              autoAdjustHeight: false,
                              hint: 'Your text here...',
                              shouldEnsureVisible: true),
```

**Comment by truly6ve** [comment]
It is sorted ...

**Comment by boziyoung** [comment]
hi, i am running my app in flutter for web, it still raises this error

` Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19044.1706], locale zh-CN)
    • Flutter version 2.10.1 at D:\Program Files\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (3 months ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[X] Android toolchain - develop for Android devices
    X ANDROID_HOME = D:\Downloads\platform-tools_r31.0.3-windows\platform-tools
      but Android SDK not found at this location.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.47

[√] HTTP Host Availability
    • All required HTTP hosts are available`

my code :
`child:  HtmlEditor(
                controller: controller,
                htmlEditorOptions: const HtmlEditorOptions(
                              autoAdjustHeight: false,
                              hint: 'Your text here...',
                              shouldEnsureVisible: true),`

**Comment by reke592** [comment]
still having issue with CSP headers
![image](https://github.com/tneotia/html-editor-enhanced/assets/17094894/a8c2a1e7-de48-49b3-9bd3-568c47c11469)

**Comment by acheronian** [comment]
Having the same issue, csp generator detected multiple inline style-src resources.

> still having issue with CSP headers ![image](https://private-user-images.githubusercontent.com/17094894/262216999-a8c2a1e7-de48-49b3-9bd3-568c47c11469.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDY0MTcsIm5iZiI6MTcwODUwNjExNywicGF0aCI6Ii8xNzA5NDg5NC8yNjIyMTY5OTktYThjMmExZTctZGU0OC00OWIzLTliZDMtNTY4YzQ3YzExNDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA5MDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1M2Y4NTZlODQxNjk4MGFmYzNkMzQyYTU2NDkzNmEyZDVjODllOTBmNGRlNDI5NzVhNWVjZGQ1NWRhY2YzNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qqpK8Wx7xkkvFNgqmXcj0h3oru8mcQWl9-g3-WOoBuE)
