### ISSUE TITLE
[QUESTION] Editor don't work after flutter build web

### ISSUE THREAD

**Issue by dospringer** [tneotia/html-editor-enhanced#234]
First, thanks for the editor, this package mean a lot for me :) My problem is, when I build the app with `flutter build web` or `flutter build web --web-renderer html` the editor is not visible.

Link to app: https://signature.volt.link/#/

**Comment by dospringer** [comment]
I have tried some things, and now the toolbar works, but not the other content, I will try to find a solution and then post it here

**Comment by tneotia** [comment]
Hi Dominik, I see these errors in web console:

![image](https://user-images.githubusercontent.com/50850142/159579401-398e128a-a61e-4c1e-9df9-fb671e6bc9e8.png)

In your deployment repo do you see this file at that path?

**Comment by dospringer** [comment]
The thing is, that I have first thought too, that this the problem, but I have found the same warning in my development environment and the editor works. So I think there is another issue, to answer your question:  I can't find the file summernote-lite.min.js.map in both environments, not even in other directories.

P.S. Thank you so much for your fast reply, I really know to appreciate that 🙏

**Comment by tneotia** [comment]
@dospringer I just checked the internal HTML code, and actually we don't even try to load `summernote-lite.min.js.map`. Are you using some custom HTML or an older version of the package?

**Comment by tneotia** [comment]
Actually I think the issue is related to the PR #233. I have merged this into master - can you point your dependency to the git master branch and see if the issue is gone?

**Comment by dospringer** [comment]
I use the newest version 2.4.0+1 @tneotia

**Comment by dospringer** [comment]
When you want to take a look at the code, you can see it on https://github.com/voltbonn/signature.volt.link

**Comment by dospringer** [comment]
I have tried to load the master branch with the following code in my pubspec.yaml:
`html_editor_enhanced:
    git: https://github.com/tneotia/html-editor-enhanced.git`

Sadly, this has not solved the problem :/

**Comment by tneotia** [comment]
Just cloned the repo and ran `flutter build web`, then opened the build/web directory in VSCode to open index.html in browser, and all seems to work fine:

![image](https://user-images.githubusercontent.com/50850142/160012867-b3adc7df-e80d-4c9c-b176-f226f3436489.png)

Are you able to reproduce the issue when running the build files locally (not hosted to a server)?

**Comment by dospringer** [comment]
I try it, give me a moment

**Comment by dospringer** [comment]
Yes it work, you are right, interesting

**Comment by dospringer** [comment]
When you want, I try to find the solution and then post it here for other users
