### ISSUE TITLE
HTML editor is still loading [BUG]

### ISSUE THREAD

**Issue by cntoss** [tneotia/html-editor-enhanced#265]
**Editor did not work**
Unable to reflect changes after clicking bold, italic, underline, order list, and all toolbar buttons the respective errors are:

1. HTML editor is still loading, please wait before evaluating this JS: document.execCommand('bold', false);
2. HTML editor is still loading, please wait before evaluating this JS: document.execCommand('italic', false);
3. TML editor is still loading, please wait before evaluating this JS: document.execCommand('underline', false)
4. HTML editor is still loading, please wait before evaluating this JS: document.execCommand('insertUnorderedList', false)

**Code**

        class CustomEditor extends StatelessWidget {
             const CustomEditor({
              Key? key,
          });
      
        @override
        Widget build(BuildContext context) {
          return HtmlEditor(
            controller: HtmlEditorController(),
            htmlEditorOptions: HtmlEditorOptions(
                hint: 'hintText',
                initialText: 'hello'),
            htmlToolbarOptions: HtmlToolbarOptions(
              defaultToolbarButtons: [
                FontButtons(),
                ColorButtons(),
                ListButtons(listStyles: false),
                ParagraphButtons(
                  textDirection: false,
                  lineHeight: false,
                ),
              ],
            ),
            otherOptions: OtherOptions(),
          );
        }
     }

<details>
<summary>Flutter doctor -v</summary>
 Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-NP)
    • Flutter version 3.0.1 at /Users/ug/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ug/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 12.3 21E230 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by BurningAXE** [comment]
Constantly getting this error, too.

**Comment by cntoss** [comment]
fixed:
Problem is on HtmlEditorController
After passing HtmlEditorController as
   
    const CustomEditor({Key? key, required this.controller});

and

      HtmlEditor(
      controller: controller,
      ...

**Comment by tneotia** [comment]
Don't instantiate controller within build method

**Comment by cntoss** [comment]
> CustomEditor

      // Flutter imports:
      import 'package:flutter/material.dart';
      import 'package:html_editor_enhanced/html_editor.dart';
      
      import '../widget/custom_editor_card.dart';
      
      class TextEditorScreen extends StatefulWidget {
        const TextEditorScreen({Key? key}) : super(key: key);
      
        @override
        _UpdateVacancyScreenState createState() => _UpdateVacancyScreenState();
      }
      
      class _UpdateVacancyScreenState extends State<TextEditorScreen> {
        late HtmlEditorController _descriptionController;
      
        @override
        void initState() {
          super.initState();
      
          _descriptionController = HtmlEditorController();
        }
      
        @override
        Widget build(BuildContext context) {
          return Scaffold(
            appBar: AppBar(),
            body: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text('Description'),
                  CustomEditor(
                      controller: _descriptionController,
                      initialText: "Initial data",
                      hintText: 'Description text here'),
                  ElevatedButton(
                      onPressed: () async {
                        String? _result = await _descriptionController.getText();
                        print(_result);
                      },
                      child: Text('Submit'))
                ]),
          );
        }
      }

//CustomEditor

        class CustomEditor extends StatelessWidget {
        const CustomEditor(
            {Key? key, required this.controller, this.hintText, this.initialText});
        final HtmlEditorController controller;
        final String? hintText;
        final String? initialText;
        @override
        Widget build(BuildContext context) {
          return HtmlEditor(
            controller: controller,
            htmlEditorOptions:
                HtmlEditorOptions(hint: hintText, initialText: initialText),
            htmlToolbarOptions: HtmlToolbarOptions(
              defaultToolbarButtons: [
                FontButtons(),
                ColorButtons(),
                ListButtons(listStyles: false),
                ParagraphButtons(
                  textDirection: false,
                  lineHeight: false,
                ),
              ],
            ),
            otherOptions:
                OtherOptions(),
          );
        }
      }

**Comment by BurningAXE** [comment]
> Don't instantiate controller within build method

I don't but I am still getting this error when updating text of the controller.

**Comment by cntoss** [comment]
> > Don't instantiate controller within build method
> 
> I don't but I am still getting this error when updating text of the controller.

did you test my code

**Comment by BurningAXE** [comment]
I want to apply the fix to my code but I am not sure what the fix is. Can you post the code when it was not working?
